baseURL = "https://sordeye-running.github.io"
languageCode = "fr-br"
title = "Sordeye running!"
theme = "mediumish-gohugo-theme"
summaryLength = 0
copyright = "CTroupin - All rights reserved"
enableEmoji = true
publishDir = "docs"
assetDirs = "static"

[params]
  logo = "logo.png"
  description ="Rien de tel qu'une petite montÃ©e de la Sordeye pour se rÃ©veiller"

[params.author]
  name = "Charles Troupin"
  thumbnail = "author.jpg"
  #description = "Creator of this blog."

[params.index]
  picture = "sordeye01.jpg"
  picture404 = "barriere.jpg"
  title = "Sordeye running"
  subtitle = ""
  alertbar = false

## Main Menu
[[menu.main]]
    name = "ğŸ–Šï¸ Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "ğŸƒ Coureurs"
    weight = 200
    identifier = "coureurs"
    url = "/coureurs"
[[menu.main]]
    name = "ğŸ—ºï¸ Parcours"
    identifier = "parcours"
    weight = 400
    url = "/parcours"
[[menu.main]]
    name = "â„¹ï¸ About"
    identifier = "about"
    weight = 500
    url = "/about"
